{ self, inputs, ... }: {
  flake.nixosModules.desktopBasePackages = { pkgs, ... }: {
    environment.systemPackages = with pkgs; [
      papirus-icon-theme
      git
      neovim
      ripgrep
      fd
      fzf
      yazi
      lazygit
      gcc
      gnumake
      unzip
      curl
      python3
      nodejs
      stylua
      lua-language-server
      nil
      nixfmt-rfc-style
      wget
      brave
      kitty
      vscode
      obsidian
      qbittorrent
      discord
      teams-for-linux
      spotify
      nemo
      nautilus
      ffmpegthumbnailer
      evince
      file-roller
      wl-clipboard
      grim
      slurp
      polkit_gnome
      gemini-cli
      codex
      tmux
      just
      calibre
      fastfetch
      wdisplays
      btop
    ];
  };
}
